name: PacketWrapper
version: ${project.version}
main: com.comphenix.packetwrapper.PacketWrapper
api-version: '1.13'
depend: [ProtocolLib]
authors: [dmulloy2, Comphenix]
description: Contains wrappers for each packet in Minecraft.